"""Deliverable renderers — DOCX / XLSX with a provenance sidecar.

README Phase 1's exit criterion is a *downloadable DOCX with citations*, and
§4.11 wants every artefact accompanied by evidence. So a render here always
produces two files: the document, and a `.provenance.json` sidecar recording
which source backed each section. An engineering document whose claims cannot
be traced is exactly the output a refinery cannot accept.

Content arrives already assembled; nothing in this module talks to a model,
and no value is computed here — numbers come from `calc_engine` only.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from docx import Document as DocxDocument
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill

ACCENT = RGBColor(0xD9, 0x77, 0x57)
MUTED = RGBColor(0x66, 0x66, 0x66)


@dataclass
class Citation:
    """Where one claim came from."""

    label: str
    document: str = ""
    page: Optional[int] = None
    bbox: Optional[list[float]] = None
    source_type: str = "pid"

    def render(self) -> str:
        bits = [self.document or self.label]
        if self.page:
            bits.append(f"p.{self.page}")
        if self.bbox and len(self.bbox) == 4:
            bits.append("bbox[" + ", ".join(f"{v:.3f}" for v in self.bbox) + "]")
        return " · ".join(b for b in bits if b)

    def as_dict(self) -> dict:
        return {
            "label": self.label,
            "document": self.document,
            "page": self.page,
            "bbox": self.bbox,
            "source_type": self.source_type,
        }


@dataclass
class Section:
    heading: str
    body: str = ""
    bullets: list[str] = field(default_factory=list)
    table: Optional[dict] = None       # {"columns": [...], "rows": [[...]]}
    citations: list[Citation] = field(default_factory=list)


@dataclass
class RenderedArtifact:
    path: Path
    provenance_path: Path
    kind: str
    name: str
    citations: int

    def as_dict(self) -> dict:
        return {
            "name": self.name,
            "kind": self.kind,
            "path": str(self.path),
            "provenance_path": str(self.provenance_path),
            "citations": self.citations,
        }


def _slug(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "-", text).strip("-")[:60] or "deliverable"


def _stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")


def _write_provenance(
    out_dir: Path, stem: str, title: str, sections: list[Section], extra: dict
) -> tuple[Path, int]:
    entries = []
    for section in sections:
        for c in section.citations:
            entries.append({"section": section.heading, **c.as_dict()})
    payload = {
        "title": title,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "citations": entries,
        **extra,
    }
    path = out_dir / f"{stem}.provenance.json"
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path, len(entries)


def render_docx(
    out_dir: Path,
    title: str,
    sections: list[Section],
    subtitle: str = "",
    metadata: Optional[dict] = None,
) -> RenderedArtifact:
    """Render a cited engineering document."""
    out_dir.mkdir(parents=True, exist_ok=True)
    doc = DocxDocument()

    heading = doc.add_heading(title, level=0)
    for run in heading.runs:
        run.font.color.rgb = ACCENT
    if subtitle:
        p = doc.add_paragraph(subtitle)
        p.runs[0].font.color.rgb = MUTED
        p.runs[0].font.size = Pt(10)

    meta = doc.add_paragraph(
        f"Generated by Meshcore · {datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC} · "
        "on-premise, no external inference"
    )
    meta.runs[0].font.size = Pt(8)
    meta.runs[0].font.color.rgb = MUTED
    meta.alignment = WD_ALIGN_PARAGRAPH.LEFT

    # The status banner is deliberate: an AI-assembled engineering document is
    # a draft for a named engineer to approve, and the file should say so.
    banner = doc.add_paragraph()
    banner_run = banner.add_run("STATUS: DRAFT — REQUIRES ENGINEERING REVIEW")
    banner_run.bold = True
    banner_run.font.size = Pt(9)
    banner_run.font.color.rgb = ACCENT

    for section in sections:
        doc.add_heading(section.heading, level=1)
        if section.body:
            doc.add_paragraph(section.body)
        for bullet in section.bullets:
            doc.add_paragraph(bullet, style="List Bullet")
        if section.table:
            cols = section.table.get("columns", [])
            rows = section.table.get("rows", [])
            if cols:
                table = doc.add_table(rows=1, cols=len(cols))
                table.style = "Light Grid Accent 1"
                for i, col in enumerate(cols):
                    cell = table.rows[0].cells[i]
                    cell.text = str(col)
                    for para in cell.paragraphs:
                        for run in para.runs:
                            run.bold = True
                for row in rows:
                    cells = table.add_row().cells
                    for i, value in enumerate(row[: len(cols)]):
                        cells[i].text = "" if value is None else str(value)
        if section.citations:
            cite = doc.add_paragraph()
            run = cite.add_run(
                "Sources: " + "; ".join(c.render() for c in section.citations)
            )
            run.font.size = Pt(8)
            run.font.color.rgb = MUTED

    doc.add_page_break()
    doc.add_heading("Provenance", level=1)
    doc.add_paragraph(
        "Every statement above is traceable to an extracted source. The machine-"
        "readable record is in the .provenance.json sidecar shipped with this file."
    )
    all_cites = [c for s in sections for c in s.citations]
    if all_cites:
        table = doc.add_table(rows=1, cols=3)
        table.style = "Light Grid Accent 1"
        for i, col in enumerate(("Section", "Source", "Type")):
            table.rows[0].cells[i].text = col
        for section in sections:
            for c in section.citations:
                cells = table.add_row().cells
                cells[0].text = section.heading
                cells[1].text = c.render()
                cells[2].text = c.source_type
    else:
        doc.add_paragraph("No citations were attached to this deliverable.")

    stem = f"{_slug(title)}-{_stamp()}"
    path = out_dir / f"{stem}.docx"
    doc.save(path)
    prov_path, count = _write_provenance(
        out_dir, stem, title, sections, metadata or {}
    )
    return RenderedArtifact(
        path=path, provenance_path=prov_path, kind="docx",
        name=path.name, citations=count,
    )


def render_xlsx(
    out_dir: Path,
    title: str,
    columns: list[str],
    rows: list[list[Any]],
    citations: Optional[list[Citation]] = None,
    metadata: Optional[dict] = None,
) -> RenderedArtifact:
    """Render a tabular deliverable (instrument list, line list, tracker)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    wb = Workbook()
    ws = wb.active
    ws.title = (title[:28] or "Sheet1").replace("/", "-")

    header_fill = PatternFill("solid", fgColor="D97757")
    for i, col in enumerate(columns, start=1):
        cell = ws.cell(row=1, column=i, value=str(col))
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center")

    for r, row in enumerate(rows, start=2):
        for c, value in enumerate(row[: len(columns)], start=1):
            ws.cell(row=r, column=c, value=value)

    for i, col in enumerate(columns, start=1):
        width = max(len(str(col)), *(len(str(r[i - 1])) for r in rows)) if rows else len(str(col))
        ws.column_dimensions[ws.cell(row=1, column=i).column_letter].width = min(
            max(width + 2, 10), 52
        )
    ws.freeze_panes = "A2"

    # Sources go on their own sheet so the data sheet stays machine-readable.
    cites = citations or []
    if cites:
        src = wb.create_sheet("Sources")
        for i, col in enumerate(("Source", "Document", "Page", "Type"), start=1):
            cell = src.cell(row=1, column=i, value=col)
            cell.font = Font(bold=True)
        for r, c in enumerate(cites, start=2):
            src.cell(row=r, column=1, value=c.label)
            src.cell(row=r, column=2, value=c.document)
            src.cell(row=r, column=3, value=c.page)
            src.cell(row=r, column=4, value=c.source_type)

    stem = f"{_slug(title)}-{_stamp()}"
    path = out_dir / f"{stem}.xlsx"
    wb.save(path)
    prov_path, count = _write_provenance(
        out_dir, stem, title,
        [Section(heading=title, citations=cites)],
        metadata or {},
    )
    return RenderedArtifact(
        path=path, provenance_path=prov_path, kind="xlsx",
        name=path.name, citations=count,
    )
